### ISSUE TITLE
Uveso's long-term bugtracing

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#2045]
I am using this to track/link errors over longer time periods

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address
0x0213d267 #1803
0x023fde58 #1804
0x0047a820 #348
0x00598eec #1900
0x005f39f7 #1574 (Fixed.)
0x0067aa5f #318
0x006cbc63 #1375 (xrb0104)
0x008b94f0 #1559
0x00938ac8 #1117
0x0095854f #1445
0x009d7b75 #1467

GitHub gamebuild stability tests:
11.05.2017 (3676) part I #1969 result=perfect
12.05.2017 FAForever/deploy/faf (3677) #1971 result=stable
15.05.2017 FAForever/deploy/beta (3678) #1991 result=DEADLOOP
18.05.2017 master (3682) #2001 result=stable
29.05.2017 (3676) part II #2044 result=stable
05.06.2017  (3684) + PR AdvancedLeadTarget #2060 result=stable
06.06.2017 deploy/fafdevelop (3684) #2061 result=stable

Unknown/rare errors without error messages:

ERROR1 - count:4 last:06.Jun.2017
Freeze after transition screen while zooming to CDR.
(Transition screen is half on the way to fade out. ~50% alpha)

ERROR2 - count:3 last:13.May.2018
Crash to desktop while initiating AI Archetype
Last logline: info: *AI DEBUG: ARMY \0004\000: Initiating Archetype using SorianMainTurtle
Last logline: info: *AI DEBUG: ARMY \0001\000: Initiating Archetype using UvesoMainAdaptive
(Transition screen is half on the way to fade out. ~50% alpha)

ERROR3 - count:2 last:19.May.2018
Game Frozen after ACU kill.
Last logline: warning: ACU kill detected. Rating for ranked games is now enforced.

ERROR4 - count:1 last:05.Jun.2017
Game frozen in midgame, sound and sim still running, but UI/gfx is frozen

Last Update 30.Dec.2019
(no new errors since 06 / 2017)

**Comment by Garanas** [comment]
@KionX That is a good find - great work. Here's a few more for this issue:

-------------------

Post: https://forum.faforever.com/topic/2488/constant-game-crashes-need-help-figuring-it-out/17
Replay: 15229180
Branch: FAF
Log: [15229180.txt](https://github.com/FAForever/fa/files/7089985/15229180.txt)

Error provided by game:
```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x00438168
    attempted to read memory at 0x00000001

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15229180.log /gpgnet 127.0.0.1:20364 /mean 971.12964 /deviation 152.34543 /savereplay gpgnet://127.0.0.1:49336/15229180/Xarlus.SCFAreplay /country DE /clan NUT /numgames 59

Callstack:
	Unknown symbol (address 0x00438168)
	Unknown symbol (address 0x008026ac)
	Unknown symbol (address 0x00801e43)
```

Error provided by client:
```
java.lang.RuntimeException: Forged Alliance Crashed with exit code 1. See C:\ProgramData\FAForever\logs\game_15229180.log for more information
	at com.faforever.client.game.GameService.lambda$spawnTerminationListener$43(GameService.java:701)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

-------------------

Post: https://forum.faforever.com/topic/2488/constant-game-crashes-need-help-figuring-it-out/16
Replay: 15228945 
Branch: FAF
Log: [game_15228945.log](https://github.com/FAForever/fa/files/7089988/game_15228945.log)

Error provided by game:
```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0042323b
    attempted to write memory at 0x3c003c04

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15228945.log /gpgnet 127.0.0.1:50240 /mean 953.129 /deviation 153.206 /savereplay gpgnet://127.0.0.1:53083/15228945/Xarlus.SCFAreplay /country DE /clan NUT /numgames 58

Callstack:
	Unknown symbol (address 0x0042323b)
	Unknown symbol (address 0x00801e43)
```

Error provided by client:
```
java.lang.RuntimeException: Forged Alliance Crashed with exit code 1. See C:\ProgramData\FAForever\logs\game_15228945.log for more information
	at com.faforever.client.game.GameService.lambda$spawnTerminationListener$43(GameService.java:701)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by KionX** [comment]
I haven't studied them deeply, but all three are related to textures.

**Comment by Garanas** [comment]
Textures in what form?

**Comment by KionX** [comment]
The same method as described above.
I can make a utility for this. If it will be useful.

**Comment by Garanas** [comment]
If you could - that would be great.

![image](https://user-images.githubusercontent.com/15778155/132301700-523e2db4-a47c-4cdc-9786-5d43664ba647.png)

Another exception when playing co-op.

**Comment by KionX** [comment]
Dump file is undesirable, they are uninformative and inconvenient.
It seems that this is not a faf error.

**Comment by Garanas** [comment]
How do you make that conclusion?

And about the dump files - yes, they are inconvenient. But it is better to have one, then not have it at all.

**Comment by KionX** [comment]
The replay did not show an error, there is no AV address in the code. Perhaps it was a transition on a corrupted pointer.

**Comment by Garanas** [comment]
He has it quite often - I'll ask him to keep them coming.

**Comment by KionX** [comment]
If someone plays on Linux, let them indicate this.

**Comment by Crotalus** [comment]
@KionX @Garanas 
While looking at the bug concerning OC and killing mobile shield units I stumbled upon the hard crash above at address 0x0050dfd8.

If you do targetEntity: GetBlueprint() when targetEntity is a "shield bubble" and not the unit the game crashes hard.

```lua
OverchargeProjectile = Class() {
    OnImpact = function(self, targetType, targetEntity)
        -- This will crash the game if targetEntity is the shield bubble and not the actual shield
        targetEntity:GetBlueprint()
    end
...
}

```

Would be good if this is fixed so the game doesn't crash at least. Maybe just return nil would be better.

**Comment by Garanas** [comment]
post: https://forum.faforever.com/topic/2569/patch-3721-hotfix-3722-hotfix-3723/33
replay: 15362291
branch: FAF
similar to: https://github.com/FAForever/fa/issues/2045#issuecomment-906426363

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0050dfd8
attempted to read memory at 0x0000005c

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15362291.log /gpgnet 127.0.0.1:18519 /mean 1157.78 /deviation 110.825 /savereplay gpgnet://127.0.0.1:61428/15362291/Gobblerpl.SCFAreplay /country PL /numgames 134

Callstack:
Unknown symbol (address 0x0050dfd8)
Unknown symbol (address 0x0068af40)
Unknown symbol (address 0x3a20736f)

KionX already determined the [cause of this](https://github.com/FAForever/fa/issues/2045#issuecomment-906426363) - do we have an idea where / when this happens?

**Comment by Garanas** [comment]
post: https://forum.faforever.com/topic/2569/patch-3721-hotfix-3722-hotfix-3723/35
replay: 15366794
branch: FAF
similar to: https://github.com/FAForever/fa/issues/2045#issuecomment-906426363

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0050dfd8
attempted to read memory at 0x0000005c

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15366794.log /gpgnet 127.0.0.1:2777 /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:63574/15366794/RomanGiant06.SCFAreplay /country US /numgames 0

Callstack:
Unknown symbol (address 0x0050dfd8)
Unknown symbol (address 0x0068af40)
Unknown symbol (address 0x1c31c5fb)

**Comment by KionX** [comment]
15362291
https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/defaultcollisionbeams.lua#L196

**Comment by Garanas** [comment]
I'll try and see if I can understand how to use that properly myself.

**Comment by Garanas** [comment]
I've looked at it for a bit and I do not understand how to get to the files in question. Could you record how you do it and share that with us through Zulip? Because I'd really like to understand how to analyze these hard-crashes.

**Comment by KionX** [comment]
It's not all simple there. Enough for a whole lecture.
I have a better idea. I will make an automatic analyzer.

**Comment by Garanas** [comment]
I'm up for a lecture too 😄 

But I'll take the automatic analyzer - that on its own would help a lot too.

**Comment by KionX** [comment]
Persuaded. I'll try to make an auto analyzer first.
Then I will write a step-by-step example of crash analysis.

**Comment by Garanas** [comment]
You're a hero, can't wait to read up about it 😄

**Comment by Garanas** [comment]
And another one:

post: send private to me
replay: 15370416
branch: FAF
similar to: https://github.com/FAForever/fa/issues/2045#issuecomment-924858053

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0050dfd8
    attempted to read memory at 0x0000005c

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15370416.log /gpgnet 127.0.0.1:59226 /mean 979.938 /deviation 267.865 /savereplay gpgnet://127.0.0.1:54755/15370416/MAPster.SCFAreplay /country DE /numgames 4

Callstack:
	Unknown symbol (address 0x0050dfd8)
	Unknown symbol (address 0x0068af40)
	Unknown symbol (address 0x11a67dfb)

Last 100 lines of log...

debug: Current gametime: 00:34:30
info: UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Upgrades")
debug: Loading module '\000/units/uaa0304/uaa0304_script.lua\000'
info: UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Torpedo")
info: UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Upgrades")
debug: Loading module '\000/units/ueb4203/ueb4203_script.lua\000'
info: UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Pgen")
debug: Current gametime: 00:35:00
info: UI_Lua import("/lua/keymap/hotbuild.lua").buildAction("Shields")
debug: Current gametime: 00:35:30
debug: Loading module '\000/units/xea0002/xea0002_script.lua\000'
debug: Loading module '\000/units/ueb2302/ueb2302_script.lua\000'
debug: Current gametime: 00:36:00

**Comment by Garanas** [comment]
post: https://forum.faforever.com/topic/2586/game-crashing/3
replay: 15366391
branch: FAF
similar to: https://github.com/FAForever/fa/issues/2045#issuecomment-924858053

```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0050dfd8
attempted to read memory at 0x0000005c

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15366391.log /replay C:\ProgramData\FAForever\cache\temp.scfareplay /replayid 15366391

Callstack:
Unknown symbol (address 0x0050dfd8)
Unknown symbol (address 0x0068af40)
Unknown symbol (address 0x1925d9fb)
Unknown symbol (address 0x1925d9fb)
```

**Comment by Garanas** [comment]
@KionX To fix this particular issue, can I assume that 0x0000005c is something like a null reference where [this line](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/defaultcollisionbeams.lua#L196) refers to the fact that the C object of self has been destroyed? And that by adding an if statement checking for it, I can prevent these exceptions from happening?

**Comment by KionX** [comment]
Yes. 0x0000005c is something like a null reference.
But I did not find out why it is null and whether it belongs to the unit that self points to.
It says here that it can be nil:
https://github.com/FAForever/fa/blob/deploy/fafdevelop/engine/Sim.lua#L260

**Comment by Garanas** [comment]
Maybe it can be nil when it is specifically nil. I think if you specifically give it nil it may be fine, but now it may try to retrieve something and fail doing so.

**Comment by Garanas** [comment]
```
Unhandled exception:

bad allocation

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15391838.log /gpgnet 127.0.0.1:52659 /mean 1076.82 /deviation 97.3515 /savereplay gpgnet://127.0.0.1:56356/15391838/UnitySenpai7.SCFAreplay /country US /numgames 116

Callstack:
	Unknown symbol (address 0x008d462c)
```

**Comment by KionX** [comment]
At 12:10 minutes, desync. The address refers to the initial initialization of the game. Trash.

**Comment by Garanas** [comment]
I don't understand? What is trash about it?

**Comment by Garanas** [comment]
```
Unhandled exception:

bad allocation

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15391838.log /gpgnet 127.0.0.1:52659 /mean 1076.82 /deviation 97.3515 /savereplay gpgnet://127.0.0.1:56356/15391838/UnitySenpai7.SCFAreplay /country US /numgames 116

Callstack:
	Unknown symbol (address 0x008d462c)
```

```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0092a074
    attempted to read memory at 0xaa99214c

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15265598.log /gpgnet 127.0.0.1:59222 /mean 1155.1655 /deviation 95.35792 /savereplay gpgnet://127.0.0.1:53185/15265598/UnitySenpai7.SCFAreplay /country US /numgames 90

Callstack:
	Unknown symbol (address 0x0092a074)
	Unknown symbol (address 0x009144b0)
	Unknown symbol (address 0x0090d472)
	Unknown symbol (address 0x0090f5d0)
	Unknown symbol (address 0x166ffb7b)
```

These (and the previous post) are from the same person.

**Comment by KionX** [comment]
_I don't understand? What is trash about it?_
This does not give any idea of the problem and is not reproducible.

**Comment by Garanas** [comment]
Ah, I see. Trash indeed 😞

**Comment by KionX** [comment]
15265598
The replay is strange(and the crash was not reproduced).
It looks like the crash occurred in the general Lua function.
I think this is a problem with third-party applications.

**Comment by Garanas** [comment]
```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0067a559
    attempted to write memory at 0x00000204

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15412007.log /gpgnet 127.0.0.1:10722 /mean 1075.62 /deviation 97.4277 /savereplay gpgnet://127.0.0.1:51807/15412007/UnitySenpai7.SCFAreplay /country US /numgames 121

Callstack:
	Unknown symbol (address 0x0067a559)
```

**Comment by Garanas** [comment]
From: https://forum.faforever.com/topic/2638/game-crashes

```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x00915450
    attempted to read memory at 0x00000006

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15270520.log /replay C:\ProgramData\FAForever\cache\temp.scfareplay /replayid 15270520

Callstack:
	Unknown symbol (address 0x00915450)
```

**Comment by KionX** [comment]
15412007 and 15270520 are not reproduced.
Addresses lead to common functions.

These are their local errors.

**Comment by Garanas** [comment]
Do you have a suggestion what to tell them in order to fix it? Re-install the game?

**Comment by KionX** [comment]
Standard advice:
reinstall game, reinstall Windows/Linux, update drivers, check for viruses, update Linux/wine,
turn off antivirus, check memory, check processor, buy a new PC...

I don't have any original advice.

**Comment by Garanas** [comment]
I see - I'll keep that list in mind

**Comment by Garanas** [comment]
```
Deserialized nil table key.

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\replay.log /replay gpgnet://lobby.faforever.com/15452867/Jip.scfareplay /replayid 15452867

Callstack:
	Unknown symbol (address 0x006e4cd9)
	Unknown symbol (address 0x006e413c)
	Unknown symbol (address 0x1fe9be8f)
	Unknown symbol (address 0x62616e50)
	Unknown symbol (address 0x85105d86)
```

While watching a live replay - what?

**Comment by KionX** [comment]
_Deserialized nil table key._
It didn't happen.

This happened: [log_15452867.txt](https://github.com/FAForever/fa/files/7285132/log_15452867.txt)

**Comment by Garanas** [comment]
```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0095854f
    attempted to write memory at 0x02b80000

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15455963.log /gpgnet 127.0.0.1:xxxxx /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:xxxxx/15455963/nomads.SCFAreplay /country XX /numgames 0

Callstack:
	Unknown symbol (address 0x0095854f)
```

**Comment by Garanas** [comment]
```
Another crash, happens at every game

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x025ede58
attempted to read memory at 0x5f5ef079

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15468792.log /gpgnet 127.0.0.1:54992 /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:59961/15468792/vmkcom.SCFAreplay /country KZ /numgames 0

Callstack:
Unknown symbol (address 0x025ede58)
Unknown symbol (address 0x025de001)
BaseThreadInitThunk + 20 bytes ((Unknown)(0) + 0 bytes)
RtlGetAppContainerNamedObjectPath + 281 bytes ((Unknown)(0) + 0 bytes)
RtlGetAppContainerNamedObjectPath + 233 bytes ((Unknown)(0) + 0 bytes)
```

**Comment by KionX** [comment]
The replay did not show an error, there is no callstack addresses in the code.

**Comment by Garanas** [comment]
```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x00423221
attempted to read memory at 0xcb9b0313

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15621190.log /gpgnet 127.0.0.1:17562 /mean 1704.38 /deviation 105.288 /savereplay gpgnet://127.0.0.1:51789/15621190/HOSCHMOSCH.SCFAreplay /country DE /numgames 2486

Callstack:
Unknown symbol (address 0x00423221)
Unknown symbol (address 0x00801e43)
```

**Comment by Garanas** [comment]
I'll see if I can reproduce it with the probe

**Comment by KionX** [comment]
This is again a problem with textures. When rendering the terrain.

**Comment by Garanas** [comment]
Could you be more specific, are there too many textures (decals)? Or is a texture corrupted?

**Comment by KionX** [comment]
Is unknown.

**Comment by Garanas** [comment]
```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x005f9bc6
    attempted to read memory at 0x000004a4

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15819269.log /gpgnet 127.0.0.1:42590 /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:54433/15819269/Ovralyne.SCFAreplay /country CA /numgames 0

Callstack:
	Unknown symbol (address 0x005f9bc6)
	Unknown symbol (address 0x420bfffb)
```

Sadly, they map they play is 'unknown' - I'd say it would be part to decipher the cause when that is the case?

**Comment by KionX** [comment]
It looks like the unit is being destroyed inside the callback
https://github.com/FAForever/fa/blob/3727/units/URL0001/URL0001_script.lua#L91
I traced the call chain to
https://github.com/FAForever/fa/blob/3727/lua/sim/Unit.lua#L342
Then the pointer is set to nil.

**Comment by splitice** [comment]
Another one for the list:

```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x005f5d3e
    attempted to read memory at 0x00000008

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_16124536.log /gpgnet 127.0.0.1:25079 /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:59175/16124536/splitice.SCFAreplay /country AU /numgames 0

Callstack:
	Unknown symbol (address 0x005f5d3e)
	Unknown symbol (address 0x101a57fb)
	Unknown symbol (address 0x2a114b6b)
	Unknown symbol (address 0x006a4bab)
	Unknown symbol (address 0xccccccc7)

Last 100 lines of log...

info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: CWldSession::DoBeat() unknown entity id (0x2ff00160) supplied in a pose update.
warning: Error running OnHealthChanged script in Entity xsbx304 at 79d3cf08: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1148): attempt to loop over field `?' (a nil value)
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1148): in function `ManageDamageEffects'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1178): in function <...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua:1177>
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
debug: Current gametime: 00:31:30
warning: Error running OnHealthChanged script in Entity xsbx304 at 68e9ea08: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1148): attempt to loop over field `?' (a nil value)
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1148): in function `ManageDamageEffects'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1178): in function <...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua:1177>
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
warning: Error running lua script: Unexpected type for army object
         stack traceback:
         	[C]: in function `IsEnemy'
         	...ta\faforever\gamedata\lua.nx2\lua\ai\aiutilities.lua(3322): in function `AIFindNearestCategoryTargetInRange'
         	...ogramdata\faforever\gamedata\lua.nx2\lua\platoon.lua(10106): in function <...ogramdata\faforever\gamedata\lua.nx2\lua\platoon.lua:9829>
info: AutoReclaim: Enabling automatic mass reclaim
warning: Error running lua script: ...a\faforever\gamedata\lua.nx2\lua\effectutilities.lua(2024): Game object has been destroyed
         stack traceback:
         	[C]: in function `SetGoal'
         	...a\faforever\gamedata\lua.nx2\lua\effectutilities.lua(2024): in function <...a\faforever\gamedata\lua.nx2\lua\effectutilities.lua:1989>
warning: Error running lua script: Unexpected type for army object
         stack traceback:
         	[C]: in function `IsEnemy'
         	...ta\faforever\gamedata\lua.nx2\lua\ai\aiutilities.lua(3322): in function `AIFindNearestCategoryTargetInRange'
         	...ogramdata\faforever\gamedata\lua.nx2\lua\platoon.lua(10106): in function <...ogramdata\faforever\gamedata\lua.nx2\lua\platoon.lua:9829>
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
warning: Error running OnHealthChanged script in Entity xsbx304 at 79d3cf08: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1182): attempt to loop over field `DamageEffectsBag' (a nil value)
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1182): in function `DestroyAllDamageEffects'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1152): in function `ManageDamageEffects'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1178): in function <...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua:1177>
warning: Error running OnStopBeingBuilt script in Entity xsbx304 at 79d3cf08: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2310): attempt to call method `AddUnitStat' (a nil value)
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2310): in function `OnStopBeingBuilt'
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(1594): in function <...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua:1593>
warning: Error running lua script: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2358): attempt to call method `Destroy' (a nil value)
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2358): in function `StopBeingBuiltEffects'
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(1567): in function <...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua:1566>
warning: Error running OnStartBuild script in Entity xsbx304 at 79d3cf08: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(723): table index is nil
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(723): in function `OnStartRepair'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2615): in function `OnStartBuild'
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(2088): in function <...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua:2084>
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Enabling automatic mass reclaim
info: AutoReclaim: Halting automatic mass reclaim
warning: Error running OnHealthChanged script in Entity xsbx304 at 68e9ea08: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1182): attempt to loop over field `DamageEffectsBag' (a nil value)
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1182): in function `DestroyAllDamageEffects'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1152): in function `ManageDamageEffects'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1178): in function <...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua:1177>
warning: Error running OnStopBeingBuilt script in Entity xsbx304 at 68e9ea08: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2310): attempt to call method `AddUnitStat' (a nil value)
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2310): in function `OnStopBeingBuilt'
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(1594): in function <...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua:1593>
warning: Error running lua script: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2358): attempt to call method `Destroy' (a nil value)
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2358): in function `StopBeingBuiltEffects'
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(1567): in function <...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua:1566>
warning: Error running OnStartBuild script in Entity xsbx304 at 68e9ea08: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(723): table index is nil
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(723): in function `OnStartRepair'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2615): in function `OnStartBuild'
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(2088): in function <...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua:2084>
```

**Comment by Uveso** [comment]
@splitice,

thanks for reporting the error.
Please disable all mods in your game and test again if the error persists.

In case you have the error at 0x005f5d3e at least 2 times without mods, please report it back here.
